CREATE DATABASE IF NOT EXISTS XFACTO_AI;

CREATE SCHEMA IF NOT EXISTS XFACTO_AI.RAW;
CREATE SCHEMA IF NOT EXISTS XFACTO_AI.CURATED;
CREATE SCHEMA IF NOT EXISTS XFACTO_AI.MART;
CREATE SCHEMA IF NOT EXISTS XFACTO_AI.AUDIT;