CREATE OR REPLACE FILE FORMAT XFACTO_AI.RAW.CSV_FILE_FORMAT
    TYPE = CSV
    FIELD_DELIMITER = ','
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    SKIP_HEADER = 1
    NULL_IF = ('', 'NULL', 'NaN')
    EMPTY_FIELD_AS_NULL = TRUE;