-- power BI dashboard views

CREATE OR REPLACE VIEW XFACTO_AI.MART.DIM_TICKER AS
SELECT DISTINCT ticker
FROM XFACTO_AI.MART.STOCK_DAILY_INSIGHTS;

CREATE OR REPLACE VIEW XFACTO_AI.MART.DIM_DATE AS
SELECT DISTINCT trade_date AS DATE_KEY,
         YEAR(trade_date) AS YEAR,
         MONTH(trade_date) AS MONTH,
         DAY(trade_date) AS DAY,
         TO_CHAR(trade_date, 'YYYY-MM') AS YEAR_MONTH
FROM XFACTO_AI.MART.STOCK_DAILY_INSIGHTS;

CREATE OR REPLACE VIEW XFACTO_AI.MART.FACT_STOCK_DAILY_INSIGHTS AS
SELECT * FROM XFACTO_AI.MART.STOCK_DAILY_INSIGHTS;

CREATE OR REPLACE VIEW XFACTO_AI.MART.FACT_STOCK_MARKET_INSIGHTS AS
SELECT * FROM XFACTO_AI.MART.STOCK_MARKET_INSIGHTS;

SELECT * FROM XFACTO_AI.MART.FACT_STOCK_MARKET_INSIGHTS;